// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyWhitelistRules(arg1) {
    return window['go']['gui']['App']['ApplyWhitelistRules'](arg1);
}

export function GetAlerts() {
    return window['go']['gui']['App']['GetAlerts']();
}

export function GetAncestors(arg1) {
    return window['go']['gui']['App']['GetAncestors'](arg1);
}

export function GetLearningStatus() {
    return window['go']['gui']['App']['GetLearningStatus']();
}

export function GetProbeInfo() {
    return window['go']['gui']['App']['GetProbeInfo']();
}

export function GetSystemStats() {
    return window['go']['gui']['App']['GetSystemStats']();
}

export function StartLearning(arg1) {
    return window['go']['gui']['App']['StartLearning'](arg1);
}

export function StopLearning() {
    return window['go']['gui']['App']['StopLearning']();
}

