// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import { gui } from '../models';

export function ApplyWhitelistRules(arg1: number[]): Promise<void>;

export function GetAlerts(): Promise<gui.FrontendAlert[]>;

export function GetAncestors(arg1: number): Promise<gui.ProcessInfoDTO[]>;

export function GetLearningStatus(): Promise<gui.LearningStatusDTO>;

export function GetProbeInfo(): Promise<{ [key: string]: string }[]>;

export function GetSystemStats(): Promise<gui.SystemStatsDTO>;

export function StartLearning(arg1: number): Promise<void>;

export function StopLearning(): Promise<gui.RuleDTO[]>;

