// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export namespace gui {
  export interface FrontendAlert {
    id: string;
    timestamp: number;
    severity: string;
    ruleName: string;
    description: string;
    pid: number;
    processName: string;
    parentName: string;
    cgroupId: string;
  }

  export interface FrontendConnectEvent {
    type: string;
    timestamp: number;
    pid: number;
    cgroupId: string;
    family: number;
    port: number;
    addr: string;
  }

  export interface FrontendExecEvent {
    type: string;
    timestamp: number;
    pid: number;
    ppid: number;
    cgroupId: string;
    comm: string;
    parentComm: string;
  }

  export interface FrontendFileEvent {
    type: string;
    timestamp: number;
    pid: number;
    cgroupId: string;
    flags: number;
    filename: string;
  }

  export interface LearningStatusDTO {
    active: boolean;
    startTime: number;
    duration: number;
    patternCount: number;
    execCount: number;
    fileCount: number;
    connectCount: number;
    remainingSeconds: number;
  }

  export interface ProcessInfoDTO {
    pid: number;
    ppid: number;
    comm: string;
    cgroupId: string;
    timestamp: number;
  }

  export interface RuleDTO {
    name: string;
    description: string;
    severity: string;
    action: string;
    yaml: string;
    selected: boolean;
  }

  export interface SystemStatsDTO {
    processCount: number;
    workloadCount: number;
    eventsPerSec: number;
    alertCount: number;
    probeStatus: string;
  }

  export interface WorkloadDTO {
    id: string;
    cgroupPath: string;
    execCount: number;
    fileCount: number;
    connectCount: number;
    alertCount: number;
    firstSeen: number;
    lastSeen: number;
  }
}

